apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
commonLabels:
  env: production
resources:
  - ../../base/podinfo
  - namespace.yaml
images:
  - name: stefanprodan/podinfo
    newName: stefanprodan/podinfo
    newTag: 3.2.0
