apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webapp
resources:
  - ../../base/frontend
transformers:
  - labels.yaml
images:
  - name: stefanprodan/podinfo
    newName: stefanprodan/podinfo
    newTag: 3.2.1
